//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPresence.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CoreResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebPresence.Common.Resources.CoreResources", typeof(CoreResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in the copy of enumerables.
        /// </summary>
        public static string EnumerableCopyError {
            get {
                return ResourceManager.GetString("EnumerableCopyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All filters must have the same parameter.
        /// </summary>
        public static string FilterParameterName {
            get {
                return ResourceManager.GetString("FilterParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter must have 1 parameter.
        /// </summary>
        public static string FilterParameterNumber {
            get {
                return ResourceManager.GetString("FilterParameterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Add(T) or AddLast(T) method in enumerable.
        /// </summary>
        public static string NoAddInEnumerable {
            get {
                return ResourceManager.GetString("NoAddInEnumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerable of type {0} has neither () not (int) constructor.
        /// </summary>
        public static string NoConstructor {
            get {
                return ResourceManager.GetString("NoConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} has no 0 arguments constructor.
        /// </summary>
        public static string NoConstructorZero {
            get {
                return ResourceManager.GetString("NoConstructorZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ViewModel of the template cannot be a generic type.
        /// </summary>
        public static string NotIstantiatedType {
            get {
                return ResourceManager.GetString("NotIstantiatedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerables of type {0} are not supported.
        /// </summary>
        public static string NotSupportedEnumerable {
            get {
                return ResourceManager.GetString("NotSupportedEnumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerables are non supported by {0}.
        /// </summary>
        public static string NotSupportedEnumerables {
            get {
                return ResourceManager.GetString("NotSupportedEnumerables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interfaces are not supported by {0}.
        /// </summary>
        public static string NotSupportedInterface {
            get {
                return ResourceManager.GetString("NotSupportedInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Name: {0} cannot be of Type: {1}..
        /// </summary>
        public static string PropertyNameTypeError {
            get {
                return ResourceManager.GetString("PropertyNameTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} has no property named {1}.
        /// </summary>
        public static string PropertyNotFound {
            get {
                return ResourceManager.GetString("PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates must be either partial views names or Func&lt;HtmlHelper&lt;T&gt;, HelperResult&gt;,  or Func&lt;HtmlHelper&lt;T&gt;, string&gt;.
        /// </summary>
        public static string templateNotValid {
            get {
                return ResourceManager.GetString("templateNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only a  Func&lt;HtmlHelper&lt;T&gt;, HelperResult&gt;,  or Func&lt;HtmlHelper&lt;T&gt;, string&gt; template is accepted.
        /// </summary>
        public static string TypeSafeTemplateNotValid {
            get {
                return ResourceManager.GetString("TypeSafeTemplateNotValid", resourceCulture);
            }
        }
    }
}
