//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPresence.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using WebPresence.Domain.Model;
    
    public partial class WebPresenceEntities : DbContext
    {
        public WebPresenceEntities()
            : base("name=WebPresenceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<PhotoBook> PhotoBooks { get; set; }
        public virtual DbSet<WebPresence.Domain.Model.Type> Types { get; set; }
    }
}
